### ISSUE TITLE
what if you don't find the song?

### ISSUE THREAD

**Issue by aleksd-dfds** [Aswini-D3/hyf-homework#6]
https://github.com/Aswini-D3/hyf-homework/blob/10c7503bfa31c5cec5310e827d00472be2a24127/javascript/javascript1/week3/myFavoriteSongs.js#L56

Think about this: What are you pushing into the array if you don't find the song? Better yet, test it yourself. Then try to do the solution for that case.

**Comment by Aswini-D3** [comment]
here I got the changes...
const songDatabase = [{
  songId: 1,
  title: 'My baby',
  artist: 'Soggy socks',
},
{
  songId: 2,
  title: '3 nails in wood',
  artist: 'The carpenters',
},
{
  songId: 3,
  title: 'Blacker than black',
  artist: 'Instant coffee',
},
{
  songId: 4,
  title: 'When is enough too little?',
  artist: 'The spies girls',
},
];
const song1 = new Object();
song1.songId = 5;
song1.title = "Summer of 69";
song1.artist = "Bryan Adams";

const song2 = new Object();
song2.songId = 6;
song2.title = "Cheap Thrills";
song2.artist = "Sia";


const myPlaylist = [];
function addToMyPlaylist(index) {
  let newSong = songDatabase[index];
  myPlaylist.push(newSong);


}
console.log("My playlist:");

addToMyPlaylist(0);
addToMyPlaylist(3);
console.log(myPlaylist);

function addSongToDatabase(song) {
  songDatabase.push(song);
}

addSongToDatabase(song1);
addSongToDatabase(song2);
console.log(songDatabase);

function getSongByTitle(title) {
  index = songDatabase.findIndex(x => x.title === title);
  const newSearchedSong = songDatabase[index];
  return newSearchedSong;
}

const searchedSong = getSongByTitle("Cheap Thrills");
console.log(searchedSong);

const searchedSong2 = getSongByTitle("My baby");
console.log(searchedSong2);
const searchedSong3 = getSongByTitle("You're still the one");
console.log(searchedSong3);


function addSongToMyPlaylist(title) {
  index = songDatabase.findIndex(x => x.title === title);
  if (index >=0){
  const newSongToAdd = songDatabase[index];
  myPlaylist.push(newSongToAdd);
  return myPlaylist;
  }
  else{
    console.log("Can't find this title");
  }

}
addSongToMyPlaylist('3 nails in wood');
console.log(myPlaylist);
addSongToMyPlaylist('nothing else matters');
